import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/Header";
import { Toaster } from "react-hot-toast";
import StoreProvider from "@/redux/Provider";
import NextAuthProvider from "./NextAuthProvider";
import getCurrentUser from "./actions/GetCurrentUserState";
import InitialUserData from "@/components/initialUserData/InitialUserData";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Airbnb Clone",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const userDataFromServer = await getCurrentUser();

  return (
    
      <html lang="en">
        <NextAuthProvider>  
          <body className={`${poppins.className} relative`}>
            <StoreProvider>
              <Header />
              <InitialUserData userData={userDataFromServer} />
              <Toaster position="top-center" />
              {children}
            </StoreProvider>
          </body>
        </NextAuthProvider>
      </html>
  
  );
}
